export const fontFamily = {
  black: 'Raleway-Black',
  blackItalic: 'Raleway-BlackItalic',
  extraBold: 'Raleway-ExtraBold',
  extraBoldItalic: 'Raleway-ExtraBoldItalic',
  bold: 'Raleway-Bold',
  boldItalic: 'Raleway-BoldItalic',
  semiBold: 'Raleway-SemiBold',
  semiBoldItalic: 'Raleway-SemiBoldItalic',
  medium: 'Raleway-Medium',
  mediumItalic: 'Raleway-MediumItalic',
  regular: 'Raleway-Regular',
  regularItalic: 'Raleway-RegularItalic',
  light: 'Raleway-Light',
  lightItalic: 'Raleway-LightItalic',
  extraLight: 'Raleway-ExtraLight',
  extraLightItalic: 'Raleway-ExtraLightItalic',
  thin: 'Raleway-Thin',
  thinItalic: 'Raleway-ThinItalic',
}